version: "3.9"

services:
  bot:
    build: .
    container_name: reklama_bot
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./users:/app/users
      - ./media:/app/media
      - ./sessions:/app/sessions
    environment:
      - TZ=Asia/Tashkent
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
